name: Build ARM64 Docker Image from Another Repo

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout the current repo
      uses: actions/checkout@v2  

    - name: Clone the external repository
      run: |
        REPO_URL="https://github.com/webtor-io/self-hosted.git"  
        REPO_NAME=$(basename $REPO_URL .git)  
        echo "Cloning repository: self-hosted"
        git clone $REPO_URL  
        cd self-hosted

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2  

    - name: Set up QEMU for ARM64
      uses: docker/setup-qemu-action@v2  

    - name: Build ARM64 Docker image
      run: |
        docker buildx build --platform linux/arm64 -t self-hosted . --load  

    - name: Save Docker image as tar
      run: |
        docker save -o self-hosted-hosted.tar  


    - name: Upload Docker image artifact
      uses: actions/upload-artifact@v4
      with:
        name: self-hosted  
        path: self-hosted.tar  
