name: Build Docker iperf3 Image and Upload to Docker Registry

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push the Docker image for amd64
        run: |
          docker buildx build --platform linux/amd64 -t mick2019/iperf3:amd64 --push .

      - name: Build and push the Docker image for arm64
        run: |
          docker buildx build --platform linux/arm64 -t mick2019/iperf3:arm64 --push .

      - name: Build and push the multi-architecture manifest
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t mick2019/iperf3:latest --push .
