name: Build ARM64 Docker Image from Another Repo

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout the current repo
      uses: actions/checkout@v2  

    - name: Clone the external repository
      run: |

        git clone https://github.com/webtor-io/self-hosted.git 
        cd self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build the Docker image
        run: |
          docker buildx build --platform linux/amd64 -t self-hosted --load .
      - name: Save Docker image as tar
        run: |
          docker save self-hosted -o self-hosted.tar
      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: self-hosted
          path: self-hosted.tar 
